name: tenor
description: Fetch Tenor Gifs on dart client and server + on Flutter.
version: 1.0.5
homepage: https://github.com/justkawal/tenor

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  universal_io: ^2.0.0-nullsafety.2
  equatable: ^2.0.0

dev_dependencies:
  pedantic: 1.11.0
