name: tenor
description: Fetch, Search Tenor Gifs on dart client and server + on Flutter. Request for popular suggestions or categories amoung users around the world.
version: 1.0.7
homepage: https://github.com/justkawal/tenor

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.13
  universal_io: ^1.0.2
  equatable: ^1.2.6

dev_dependencies:
  pedantic: 1.11.0
