name: tenor
description: Fetch Tenor Gifs on dart client and server + on Flutter.
version: 1.0.1
homepage: https://kawal.dev

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  collection: ^1.14.13

dev_dependencies:
  pedantic: 1.9.0
